### ISSUE TITLE
Dependency "ChromeCastCore" has no shared framework schemes

### ISSUE THREAD

**Issue by muescha** [insidegui/ChromeCastCore#3]
what i do:
- i called `./bootstrap.sh` for WWDC app

what i see:
```
*** Downloading ChromeCastCore.framework binary at "Version 0.1"
*** xcodebuild output can be found in /var/folders/0j/6_kmjc_51bv7nn26xx2dvrdm0000gn/T/carthage-xcodebuild.hOFSCd.log
*** Skipped building ChromeCastCore due to the error:
Dependency "ChromeCastCore" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/insidegui/ChromeCastCore/issues/new
```

PS:
in `carthage-xcodebuild.hOFSCd.log` i found only lines with`IGListKit` but not with `ChromeCastCore`

**Comment by leibaozai** [comment]
I have this problem, too

and what i see：

> *** Checking out RxRealm at "0.5.2"
*** xcodebuild output can be found in /var/folders/32/r2b894q14d1gcyvgqysxztwm0000gn/T/carthage-xcodebuild.rrfiX4.log
*** Skipped building ChromeCastCore due to the error:
Dependency "ChromeCastCore" has no shared framework schemes
If you believe this to be an error, please file an issue with the maintainers at https://github.com/insidegui/ChromeCastCore/issues/new
*** Building scheme "IGListKit-macOS" in IGListKit.xcworkspace
*** Building scheme "IGListKit-tvOS" in IGListKit.xcworkspace
*** Building scheme "IGListKit" in IGListKit.xcworkspace
>

**Comment by insidegui** [comment]
Xcode version?

**Comment by leibaozai** [comment]
Xcode  Version 9.0 beta 6 (9M214v)

**Comment by insidegui** [comment]
Building is not supported in Xcode 9 yet, we're working on that here: https://github.com/insidegui/WWDC/pull/314
